[phases.setup]
# Instala las dependencias
commands = ["pip install -r requirements.txt"]

[phases.install]
# Ejecuta migraciones y recopila archivos estáticos
commands = [
  "python manage.py migrate",
  "python manage.py collectstatic --noinput"
]

[phases.start]
# Inicia el servidor con Gunicorn
commands = ["gunicorn cabigote.wsgi:application --bind 0.0.0.0:$PORT"]
