# Generated by Django 5.2.7 on 2026-02-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeespecial',
            name='lottie_file',
            field=models.CharField(blank=True, help_text='Ruta en static, ej: lottie/vacation.json', max_length=200),
        ),
        migrations.AddField(
            model_name='mensajeespecial',
            name='show_lottie',
            field=models.BooleanField(default=False),
        ),
    ]
