# Generated by Django 5.1.5 on 2025-10-03 02:31

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(default=django.utils.timezone.now, verbose_name='Día')),
                ('total_citas', models.IntegerField(default=0, verbose_name='Total de citas')),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Ingresos totales')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Reporte diario',
                'verbose_name_plural': 'Reportes diarios',
                'ordering': ('-dia',),
                'indexes': [models.Index(fields=['dia'], name='idx_reportediario_dia'), models.Index(fields=['creado_el'], name='idx_reportediario_creado')],
                'constraints': [models.UniqueConstraint(fields=('dia',), name='uniq_reportediario_dia')],
            },
        ),
        migrations.CreateModel(
            name='ReporteMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(default=django.utils.timezone.now, verbose_name='Mes')),
                ('total_citas', models.IntegerField(default=0, verbose_name='Total de citas')),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Ingresos totales')),
                ('ingresos_proyectados', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Ingresos proyectados')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Reporte mensual',
                'verbose_name_plural': 'Reportes mensuales',
                'ordering': ('-mes',),
                'indexes': [models.Index(fields=['mes'], name='idx_reportemensual_mes'), models.Index(fields=['creado_el'], name='idx_reportemensual_creado')],
                'constraints': [models.UniqueConstraint(fields=('mes',), name='uniq_reportemensual_mes')],
            },
        ),
    ]
