# Generated by Django 5.1.4 on 2025-01-09 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(default=django.utils.timezone.now, verbose_name='Día')),
                ('total_citas', models.IntegerField(default=0, verbose_name='Total de citas')),
                ('ingresos_totales', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ingresos totales')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
        ),
    ]
